services:
  - type: web
    name: translation-tool-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: translation-tool-db
          property: connectionString
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GITHUB_CALLBACK_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        sync: false

databases:
  - name: translation-tool-db
    databaseName: translation_tool
    user: translation_user
    plan: free